version: 1.20.1.{build}
branches:
  only:
  - default
clone_folder: c:\projects\Npackd
environment:
  version: 1.20.1
  matrix:
  - bits: 32
    prg: npackdcl
  - bits: 64
    prg: npackd
  - bits: 32
    prg: npackd
install:
- AppVeyorInstall.bat
build_script:
- AppVeyorBuild.bat
test_script:
- AppVeyorTest.bat